name: "Yves Vandewoude's personal site"
favicon: null
layout_spectrum: 0.88892
typography_spectrum: 0.5568243656307459
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4d6c90'
    - '#828f9f'
    - '#a9bbcd'
    - '#f0f5f6'
  brandStrength: 0.4375
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.47326891287229955
purpose: []
